# Maintainer: Guillermo Salgado <g.salgado04@ufromail.cl>
#
# Everything under /usr/share/plymouth/themes/omarchy-minimal is GENERATED by
# build-theme.py, and the Limine wallpaper by build-limine.py, so this package
# builds its assets from source rather than shipping them. That keeps the
# repository to a handful of files and makes the geometry reproducible.

pkgname=omarchy-plymouth-nier
pkgver=1.1.0
pkgrel=1
pkgdesc="NieR-inspired theme for the Omarchy boot chain: Limine menu, LUKS unlock and shutdown screens"
arch=('any')
url="https://github.com/Willi005/omarchy-plymouth-nier"
license=('MIT')
depends=('plymouth')
makedepends=('python' 'imagemagick' 'fontconfig' 'noto-fonts-cjk'
             'ttf-jetbrains-mono-nerd')
install="$pkgname.install"
source=('build-theme.py' 'build-limine.py' 'theme.conf' 'LICENSE')
sha256sums=('SKIP' 'SKIP' 'SKIP' 'SKIP')

_theme=omarchy-minimal

build() {
    # Renders every asset at its exact final pixel size for THIS machine's
    # panel: nothing antialiased is ever scaled at runtime, because Plymouth's
    # Image.Scale is a nearest-neighbour sampler and destroys artwork. The
    # screen size, the name on the greeting and the background word come from
    # theme.conf, and each can be overridden from the environment, e.g.
    #     PLYMOUTH_NAME="Ada" makepkg -sif
    python3 "$srcdir/build-theme.py" "$srcdir/theme"

    # The Limine menu is a 1-bit character grid, so its only artwork is the
    # wallpaper behind the text. Geometry is a fraction of the shorter side,
    # and the font scale targets ~115 columns, so both follow the panel.
    python3 "$srcdir/build-limine.py" "$srcdir/limine"
}

package() {
    install -dm755 "$pkgdir/usr/share/plymouth/themes/$_theme"
    install -m644 -t "$pkgdir/usr/share/plymouth/themes/$_theme" "$srcdir/theme/"*
    install -dm755 "$pkgdir/usr/share/$pkgname/limine"
    install -m644 -t "$pkgdir/usr/share/$pkgname/limine" "$srcdir/limine/"*

    install -Dm644 "$srcdir/LICENSE" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
