# Maintainer: Guillermo Salgado <g.salgado04@ufromail.cl>
#
# Everything under /usr/share/plymouth/themes/omarchy-minimal is GENERATED by
# build-theme.py, so this package builds the 206 assets from source rather
# than shipping them. That keeps the repository to a handful of files and
# makes the geometry reproducible.

pkgname=omarchy-plymouth-nier
pkgver=1.0.0
pkgrel=1
pkgdesc="NieR-inspired Plymouth theme for the Omarchy LUKS unlock and shutdown screens"
arch=('any')
url="https://github.com/gsm/omarchy-plymouth-nier"
license=('MIT')
depends=('plymouth')
makedepends=('python' 'imagemagick' 'noto-fonts-cjk' 'ttf-jetbrains-mono-nerd-basic')
install="$pkgname.install"
source=('build-theme.py')
sha256sums=('SKIP')

_theme=omarchy-minimal

build() {
    # Renders every asset at its exact final pixel size for a 2880x1800 panel.
    # Nothing antialiased is ever scaled at runtime: Plymouth's Image.Scale is
    # a nearest-neighbour sampler and destroys artwork.
    python3 "$srcdir/build-theme.py" "$srcdir/theme"
}

package() {
    install -dm755 "$pkgdir/usr/share/plymouth/themes/$_theme"
    install -m644 -t "$pkgdir/usr/share/plymouth/themes/$_theme" "$srcdir/theme/"*
}
