# Maintainer: Guillermo Salgado <g.salgado04@ufromail.cl>
#
# Everything under /usr/share/plymouth/themes/omarchy-minimal is GENERATED by
# build-theme.py, and the Limine wallpaper by build-limine.py, so this package
# builds its assets from source rather than shipping them. That keeps the
# repository to a handful of files and makes the geometry reproducible.

pkgname=omarchy-plymouth-nier
pkgver=1.6.0
pkgrel=1
pkgdesc="NieR-inspired theme for the Omarchy boot chain: Limine menu, LUKS unlock and shutdown screens"
arch=('any')
url="https://github.com/Willi005/omarchy-plymouth-nier"
license=('MIT')
depends=('plymouth')
optdepends=('python: required by omarchy-nier-reconfigure, and lets an upgrade
             notice that the packaged artwork was built from other settings'
            'imagemagick: required by omarchy-nier-reconfigure'
            'fontconfig: required by omarchy-nier-reconfigure'
            'noto-fonts-cjk: the katakana and the background word'
            'ttf-jetbrains-mono-nerd: every line of Latin text in the theme')
backup=('etc/omarchy-plymouth-nier.conf')
makedepends=('python' 'imagemagick' 'fontconfig' 'noto-fonts-cjk'
             'ttf-jetbrains-mono-nerd')
install="$pkgname.install"
source=('build-theme.py' 'build-limine.py' 'nierconf.py' 'theme.conf'
        'limine-splice.sh' 'plymouth-stake.sh' 'omarchy-nier-reconfigure'
        'omarchy-nier-stake'
        '85-omarchy-plymouth-nier-claim.hook'
        '99-omarchy-plymouth-nier-rebuild.hook'
        'LICENSE')
sha256sums=('SKIP' 'SKIP' 'SKIP' 'SKIP' 'SKIP' 'SKIP' 'SKIP' 'SKIP' 'SKIP'
            'SKIP' 'SKIP')

# Where the source files land under $srcdir. Empty here, because makepkg copies
# local sources straight in; the AUR flavour downloads a release tarball, so
# everything is one directory deeper. Keeping that difference in one literal
# makes aur/sync.sh a three-line rewrite rather than a fork that can drift.
# It has to be a literal, not "$srcdir": that is not set when this is parsed.
_srcsub=

_theme=omarchy-minimal

build() {
    # Renders every asset at its exact final pixel size for THIS machine's
    # panel: nothing antialiased is ever scaled at runtime, because Plymouth's
    # Image.Scale is a nearest-neighbour sampler and destroys artwork. The
    # screen size, the name on the greeting and the background word come from
    # theme.conf, and each can be overridden from the environment, e.g.
    #     PLYMOUTH_NAME="Ada" makepkg -sif
    python3 "$srcdir$_srcsub/build-theme.py" "$srcdir/theme"

    # The Limine menu is a 1-bit character grid, so its only artwork is the
    # wallpaper behind the text. Geometry is a fraction of the shorter side,
    # and the font scale targets ~115 columns, so both follow the panel.
    python3 "$srcdir$_srcsub/build-limine.py" "$srcdir/limine"
}

package() {
    install -dm755 "$pkgdir/usr/share/plymouth/themes/$_theme"
    # built-for records the panel the artwork was rasterised for; it belongs
    # next to the generators, not in the theme Plymouth loads.
    install -Dm644 "$srcdir/theme/built-for" "$pkgdir/usr/share/$pkgname/built-for"
    rm "$srcdir/theme/built-for"
    install -m644 -t "$pkgdir/usr/share/plymouth/themes/$_theme" "$srcdir/theme/"*
    install -dm755 "$pkgdir/usr/share/$pkgname/limine"
    install -m644 -t "$pkgdir/usr/share/$pkgname/limine" "$srcdir/limine/"*

    # The generators ship too, because omarchy-nier-reconfigure re-runs them
    # whenever /etc/omarchy-plymouth-nier.conf changes.
    install -dm755 "$pkgdir/usr/share/$pkgname"
    install -m644 -t "$pkgdir/usr/share/$pkgname" \
        "$srcdir$_srcsub/build-theme.py" "$srcdir$_srcsub/build-limine.py" "$srcdir$_srcsub/nierconf.py" \
        "$srcdir$_srcsub/limine-splice.sh" "$srcdir$_srcsub/plymouth-stake.sh"
    install -Dm755 "$srcdir$_srcsub/omarchy-nier-reconfigure" \
        "$pkgdir/usr/bin/omarchy-nier-reconfigure"
    install -Dm644 "$srcdir$_srcsub/theme.conf" \
        "$pkgdir/etc/omarchy-plymouth-nier.conf"

    # An `omarchy update` resets /etc/plymouth/plymouthd.conf back to the
    # stock theme -- omarchy-settings does it deliberately on every upgrade --
    # so the theme has to re-stake its claim from a pacman hook afterwards.
    # 85 repairs the config ahead of 90-mkinitcpio-install.hook, 99 rebuilds
    # the boot image only if nothing else in the transaction already did.
    install -Dm755 "$srcdir$_srcsub/omarchy-nier-stake" \
        "$pkgdir/usr/share/libalpm/scripts/omarchy-nier-stake"
    install -Dm644 "$srcdir$_srcsub/85-omarchy-plymouth-nier-claim.hook" \
        "$pkgdir/usr/share/libalpm/hooks/85-omarchy-plymouth-nier-claim.hook"
    install -Dm644 "$srcdir$_srcsub/99-omarchy-plymouth-nier-rebuild.hook" \
        "$pkgdir/usr/share/libalpm/hooks/99-omarchy-plymouth-nier-rebuild.hook"

    install -Dm644 "$srcdir$_srcsub/LICENSE" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
