#!/usr/bin/env python3
"""Generate gtk.css so GTK4/libadwaita apps follow the theme's palette.

Omarchy does not theme GTK apps from the palette. omarchy-theme-set-gnome sets
exactly three things: `color-scheme` and `gtk-theme` to a hardcoded Adwaita or
Adwaita-dark from the theme's `mode`, and `icon-theme` from its `icons.theme`.
So a file manager under any Omarchy theme is stock GNOME in light or dark, and
the only colour the theme picks there is the folder icon.

libadwaita does not read `gtk-theme` at all -- the supported way to recolour it
is overriding its named colours in ~/.config/gtk-4.0/gtk.css. That is what this
generates, one file per theme, staged by Omarchy with the rest of the theme and
installed by the `gtk-colors` theme-set hook.

Scope worth stating plainly: this covers GTK4/libadwaita, which is Nautilus and
most current GNOME apps. GTK3 apps do not read these names and stay as Adwaita.

    python3 build-gtk.py [theme ...]
"""

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
THEMES = HERE / "themes"


def read_colors(path):
    out = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, _, v = line.partition("=")
        out[k.strip()] = v.strip().strip('"')
    return out


def _lin(c):
    c /= 255
    return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4


def _lum(hexcol):
    h = hexcol.lstrip("#")
    r, g, b = (_lin(int(h[i:i + 2], 16)) for i in (0, 2, 4))
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def contrast(a, b):
    la, lb = _lum(a), _lum(b)
    hi, lo = max(la, lb), min(la, lb)
    return (hi + 0.05) / (lo + 0.05)


def dim_against(bg, candidates, floor=4.5):
    """The dimmest candidate that still reads as text on `bg`.

    A rule rather than a hand-picked value, because the right answer differs
    per palette: Nier Black's dark_foreground is 2.53:1 against its ground,
    which is fine for a hairline and unusable for a filename, while Flexoki
    Light Alt's sits at 3.77:1. Sorting by contrast and taking the first that
    clears the floor keeps secondary text legible in both without either
    palette being special-cased.
    """
    ok = sorted(((contrast(c, bg), c) for c in candidates if c),
                key=lambda t: t[0])
    for ratio, colour in ok:
        if ratio >= floor:
            return colour
    return ok[-1][1] if ok else candidates[0]


def rgba(hexcol, alpha):
    h = hexcol.lstrip("#")
    r, g, b = (int(h[i:i + 2], 16) for i in (0, 2, 4))
    return f"rgba({r}, {g}, {b}, {alpha})"


TEMPLATE = """\
/* {name} -- GTK4/libadwaita colours, generated by build-gtk.py.
 *
 * Do not edit here: this file is regenerated from colors.toml. It is installed
 * to ~/.config/gtk-4.0/gtk.css by the `gtk-colors` theme-set hook, and removed
 * again when you switch to a theme that does not ship one.
 *
 * libadwaita ignores gtk-theme, so overriding these named colours is the
 * supported way to recolour it. GTK3 apps do not read these and stay Adwaita.
 *
 * Apps read this at startup -- reopen the file manager to see a change.
 */

@define-color window_bg_color {window_bg};
@define-color window_fg_color {fg};
@define-color view_bg_color {view_bg};
@define-color view_fg_color {fg};

@define-color headerbar_bg_color {surface};
@define-color headerbar_fg_color {fg};
@define-color headerbar_border_color {fg};
@define-color headerbar_backdrop_color {window_bg};
@define-color headerbar_shade_color {shade};

@define-color sidebar_bg_color {surface};
@define-color sidebar_fg_color {fg};
@define-color sidebar_backdrop_color {window_bg};
@define-color sidebar_shade_color {shade};
@define-color sidebar_border_color {shade};

@define-color secondary_sidebar_bg_color {surface};
@define-color secondary_sidebar_fg_color {fg};
@define-color secondary_sidebar_backdrop_color {window_bg};
@define-color secondary_sidebar_shade_color {shade};
@define-color secondary_sidebar_border_color {shade};

@define-color card_bg_color {surface};
@define-color card_fg_color {fg};
@define-color card_shade_color {shade};

@define-color dialog_bg_color {window_bg};
@define-color dialog_fg_color {fg};
@define-color popover_bg_color {surface};
@define-color popover_fg_color {fg};
@define-color popover_shade_color {shade};

@define-color thumbnail_bg_color {view_bg};
@define-color thumbnail_fg_color {fg};

@define-color accent_bg_color {accent};
@define-color accent_fg_color {on_accent};
@define-color accent_color {accent};

@define-color destructive_bg_color {red};
@define-color destructive_fg_color {on_accent};
@define-color destructive_color {red};

@define-color success_bg_color {green};
@define-color success_fg_color {on_accent};
@define-color success_color {green};

@define-color warning_bg_color {yellow};
@define-color warning_fg_color {on_accent};
@define-color warning_color {yellow};

@define-color error_bg_color {red};
@define-color error_fg_color {on_accent};
@define-color error_color {red};

@define-color shade_color {shade};
@define-color scrollbar_outline_color {shade};

/* Secondary text: {dim} was chosen over the palette's own dim tone because it
 * is the dimmest value in this palette that still clears 4.5:1 on the window
 * background. A filename is text, not a hairline. */
.dim-label,
label.dim-label,
.caption {{
  color: {dim};
  opacity: 1;
}}

/* The selected row in the sidebar and in the file list. */
:selected,
row:selected,
gridview child:selected {{
  background-color: {selection};
  color: {fg};
}}
"""


def build(theme):
    d = THEMES / theme
    colors = d / "colors.toml"
    if not colors.exists():
        sys.exit(f"build-gtk: {theme}: no colors.toml")

    c = read_colors(colors)
    window_bg = c.get("background", "#202020")
    fg = c.get("foreground", "#e0e0e0")
    accent = c.get("accent", fg)

    # The list area sits a step off the window, the way Adwaita's view does.
    view_bg = c.get("dark_background", window_bg)
    surface = c.get("lighter_background", window_bg)

    # Text drawn ON the accent. The palette's ground is the right answer in
    # both directions: bone on near-black, paper on coffee.
    on_accent = window_bg

    dim = dim_against(window_bg, [c.get("dark_foreground"),
                                  c.get("light_foreground"),
                                  c.get("muted"), fg])

    shade = rgba(c.get("muted", fg), 0.32)

    css = TEMPLATE.format(
        name=theme.replace("-", " ").title(),
        window_bg=window_bg, view_bg=view_bg, surface=surface, fg=fg,
        accent=accent, on_accent=on_accent, dim=dim, shade=shade,
        selection=c.get("selection", surface),
        red=c.get("red", accent), green=c.get("green", accent),
        yellow=c.get("yellow", accent))

    (d / "gtk.css").write_text(css, encoding="utf-8")

    print(f"  {theme}: gtk.css  accent {accent} ({contrast(accent, window_bg):.1f}:1)"
          f"  dim {dim} ({contrast(dim, window_bg):.1f}:1)")


if __name__ == "__main__":
    wanted = sys.argv[1:] or sorted(p.name for p in THEMES.iterdir() if p.is_dir())
    for t in wanted:
        build(t)
